export const CODESLANG = {
    "EN": { "name": "English", "alt": "eng" },
    "BG": { "name": "Bulgarian", "alt": "bul" },
    "CS": { "name": "Czech", "alt": "cze" },
    "DA": { "name": "Danish", "alt": "dan" },
    "EL": { "name": "Greek", "alt": "gre" },
    "ET": { "name": "Estonian", "alt": "est" },
    "FI": { "name": "Finnish", "alt": "fin" },
    "HU": { "name": "Hungarian", "alt": "hun" },
    "JA": { "name": "Japanese", "alt": "jpn" },
    "LT": { "name": "Lithuanian", "alt": "lit" },
    "LV": { "name": "Latvian", "alt": "lav" },
    "SK": { "name": "Slovak", "alt": "slo" },
    "SL": { "name": "Slovenian", "alt": "slv" },
    "SV": { "name": "Swedish", "alt": "swe" },
    "ZH": { "name": "Chinese (PRC)", "alt": "zho-CN" },
    "ES": { "name": "Spanish", "alt": "spa" },
    "FR": { "name": "French", "alt": "fre" },
    "DE": { "name": "German", "alt": "ger" },
    "IT": { "name": "Italian", "alt": "ita" },
    "NL": { "name": "Dutch", "alt": "dut" },
    "PT-PT": { "name": "Portuguese (Portugal)", "alt": "por-PT" },
    "PT-BR": { "name": "Portuguese (Brazil)", "alt": "por-BR" },
    "RU": { "name": "Russian", "alt": "rus" },
    "ID": { "name": "Indonesian", "alt": "ind" },
    "KO": { "name": "Korean", "alt": "kor" },
    "NB": { "name": "Norwegian", "alt": "nnb" },
    "RO": { "name": "Romanian", "alt": "rum" },
    "TR": { "name": "Turkish", "alt": "tur" },
    "UK": { "name": "Ukrainian", "alt": "ukr" },
    "PL": { "name": "Polish", "alt": "pol" }
  };  